# Generated by Django 5.0.6 on 2025-09-21 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_location_sosevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sos_audio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sos_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='accounts.sosevent')),
            ],
        ),
    ]
