# Generated by Django 5.0.6 on 2025-09-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sosaudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('center_lat', models.FloatField()),
                ('center_lon', models.FloatField()),
                ('radius_m', models.FloatField(help_text='Radius in meters')),
            ],
        ),
    ]
